# Generated by Django 5.0.1 on 2024-01-31 15:27

import petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet/photos', validators=[petstagram.photos.models.MaxFileSizeValidator(limit_value=1048576)]),
        ),
    ]
