# Generated by Django 5.0.1 on 2024-02-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0004_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.petphoto'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.petphoto'),
        ),
    ]
